security:
    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            stateless: true
            http_basic: ~

    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS }
